### ISSUE TITLE
Support Android Nougat

### ISSUE THREAD

**Issue by troyjperales** [MeetMe/font-compat#5]
Looks like the FontManager is not getting initialized (which is causing immediate app crashes) on Android N:

https://github.com/MeetMe/font-compat/blob/master/library/src/main/java/com/meetme/support/fonts/FontManager.java#L46

Maybe even consider making the latest implementation the default for API version numbers greater than the latest at the time, so as to not require an update when a new OS version is released.

**Comment by troyjperales** [comment]
It looks like Nougat (Build.VERSION.SDK_INT == 24) is landing on FontManagerImpl21 instead of FontManagerImpl24:

```
java.lang.NoSuchMethodError: No virtual method addFontWeightStyle(Ljava/lang/String;IZ)Z in class Landroid/graphics/FontFamily; or its super classes (declaration of 'android.graphics.FontFamily' appears in /system/framework/framework.jar)
                                                                                           at com.meetme.support.fonts.FontManagerImpl21.makeFamilyFromParsed(FontManagerImpl21.java:68)
                                                                                           at com.meetme.support.fonts.FontManagerImpl21.init(FontManagerImpl21.java:53)
                                                                                           at com.meetme.support.fonts.FontManagerImpl21.init(FontManagerImpl21.java:44)
                                                                                           at com.meetme.support.fonts.FontManager.install(FontManager.java:66)
```

**Comment by troyjperales** [comment]
Ahh. Yes. I just saw this TODO:

https://github.com/MeetMe/font-compat/blob/master/library/src/main/java/com/meetme/support/fonts/FontManager.java#L46

**Comment by iainalba** [comment]
I have made some minor changes to fix this issue:

https://github.com/MeetMe/font-compat/pull/6

**Comment by juanchosaravia** [comment]
Just curious, after merging this PR, are you going to create a new Release version or what do you recommend for this? Thanks!

**Comment by sharathp** [comment]
any updates please? thanks

**Comment by meganoberlin** [comment]
@iainalba  - is there any further information on this ticket regarding when it will be merged? There are several teams that are affected by this change.

Thanks,

Megan

**Comment by artaex** [comment]
Please add a new version tag for this fix

**Comment by devfrey** [comment]
@jhansche Come on, we need a new release version!

**Comment by jhansche** [comment]
`1.1-SNAPSHOT` has been built and published. Please test the snapshot and confirm that this issue is resolved.

**Comment by fangzhzh** [comment]
@jhansche FYI it works for me on API 25.

thanks

**Comment by RickBoyerDev** [comment]
@jhansche - you mention above that you published an update, how do I reference it?

I tried:
compile 'com.meetme.android:font-compat:1.1-SNAPSHOT@aar'

But it fails to resolve.  Is there a different location for the SNAPSHOTS? 

Thanks!

**Comment by RickBoyerDev** [comment]
@jhansche, you can disregard my earlier question.  As I mention in [Issue 7](https://github.com/MeetMe/font-compat/issues/7), I found that Android O/8.0 now supports font resources and it was added to the support library, so no library needed.

Thanks anyway!
